import{a as A,S as M,i as c}from"./assets/vendor-BSTwZ_tR.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(o){if(o.ep)return;o.ep=!0;const n=r(o);fetch(o.href,n)}})();const y=15,P="52852396-2e2f44ee304cf9c0c54250cb9",I="https://pixabay.com/api/";async function g(e,t=1){const{data:r}=await A.get(I,{params:{key:P,q:String(e).trim(),image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:y,page:t}});return r}const b=document.getElementById("gallery"),l=document.getElementById("loader"),L=document.getElementById("load-more");let u=null;function O(){return u||(u=new M(".gallery a",{captions:!0,captionsData:"alt",captionDelay:200,animationSpeed:180,overlayOpacity:.9})),u}function E(e){if(!Array.isArray(e)||e.length===0)return;const t=e.map(({webformatURL:r="",largeImageURL:i="#",tags:o="",likes:n=0,views:a=0,comments:w=0,downloads:S=0})=>`
      <li class="card">
        <a href="${i}">
          <img src="${r}" alt="${o}" loading="lazy"/>
        </a>
        <div class="meta">
          <span>❤ Likes: <b>${n}</b></span>
          <span>👁 Views: <b>${a}</b></span>
          <span>💬 Comments: <b>${w}</b></span>
          <span>⬇ Downloads: <b>${S}</b></span>
        </div>
      </li>`).join("");b.insertAdjacentHTML("beforeend",t),O().refresh()}function R(){b.innerHTML=""}function $(){l.classList.remove("is-hidden"),l.setAttribute("aria-hidden","false")}function q(){l.classList.add("is-hidden"),l.setAttribute("aria-hidden","true")}function x(){L.classList.remove("is-hidden")}function m(){L.classList.add("is-hidden")}const p=document.getElementById("search-form"),B=document.getElementById("load-more"),_=p.querySelector('button[type="submit"]');let f="",s=1;p.addEventListener("submit",C);B.addEventListener("click",D);function d(e,{duringLoadMore:t=!1}={}){_.disabled=e,B.disabled=e,e?$():q(),!t&&e&&m()}function v(e,t){return t*y<e}function h(){m(),c.info({title:"Кінець колекції",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}async function C(e){e.preventDefault();const t=p.elements["search-text"].value.trim();if(!t){c.warning({title:"Упс",message:"Введи ключове слово перед пошуком.",position:"topRight"});return}f=t,s=1,m(),R(),d(!0);try{const r=await g(f,s),i=(r==null?void 0:r.hits)??[];if(i.length===0){c.info({title:"Нічого не знайдено",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}E(i),v(r.totalHits,s)?x():h()}catch{c.error({title:"Помилка",message:"Проблема з мережею або API. Спробуй пізніше.",position:"topRight"})}finally{d(!1)}}async function D(){s+=1,d(!0,{duringLoadMore:!0});try{const e=await g(f,s),t=(e==null?void 0:e.hits)??[];if(t.length===0){h();return}E(t),v(e.totalHits,s)||h();const r=document.querySelector(".gallery .card");if(r){const i=r.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}}catch{c.error({title:"Помилка",message:"Не вдалося завантажити наступні зображення.",position:"topRight"})}finally{d(!1)}}
//# sourceMappingURL=index.js.map
